name: build_and_test

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # This job is named 'build-and-test' and will run on the latest Ubuntu runner provided by GitHub.

    steps:
    - uses: actions/checkout@v4

      # This step checks out the repository code

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen libgmp-dev libjansson-dev libb64-dev

    - name: Run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make -j
        make check
